global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'production'
    cluster: 'main'

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
        labels:
          service: 'prometheus'

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: [ 'nginx-exporter:9113' ]
        labels:
          service: 'nginx'

  # MySQL metrics
  - job_name: 'mysql'
    static_configs:
      - targets: [ 'mysql-exporter:9187' ]
        labels:
          service: 'mysql'

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: [ 'redis-exporter:9121' ]
        labels:
          service: 'redis'

  #  Laravel app metrics
  - job_name: 'laravel-app'
    static_configs:
      - targets: [ 'laravel-app:8081' ]
        labels:
          service: 'laravel-app'